global class AllSchedulerJob implements Schedulable {
    global void execute(SchedulableContext sc) {
        // System.enqueueJob(new AllScheduler('getCustomerMaster'));
        // System.enqueueJob(new AllScheduler('getMaterialMaster'));
        // System.enqueueJob(new AllScheduler('getSalesOrderMaster'));
        // System.enqueueJob(new AllScheduler('getInvoiceMaster'));
        // System.enqueueJob(new AllScheduler('ClearingpaymentMaster'));
        // System.enqueueJob(new AllScheduler('CustomerGlMaster'));
        // System.enqueueJob(new AllScheduler('DiscountMaster'));
        // System.enqueueJob(new AllScheduler('ARCPricingMaster'));
        // System.enqueueJob(new AllScheduler('getIncoTerms'));
    }
}